# Generated by Django 4.2.7 on 2023-12-01 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TB_BEE_CAMPOS',
            fields=[
                ('idCampo', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('max', models.CharField(max_length=255)),
                ('min', models.CharField(max_length=255)),
                ('tiempo_envio', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'TB_BEE_CAMPOS',
            },
        ),
        migrations.CreateModel(
            name='TB_BEE_MEDIDAS',
            fields=[
                ('idMedida', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('idCampo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage.tb_bee_campos')),
            ],
            options={
                'db_table': 'TB_BEE_MEDIDAS',
            },
        ),
        migrations.CreateModel(
            name='TB_BEE_CANALES',
            fields=[
                ('idCanal', models.BigAutoField(primary_key=True, serialize=False)),
                ('apiKey', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TB_BEE_CANALES',
            },
        ),
        migrations.AddField(
            model_name='tb_bee_campos',
            name='idCanal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage.tb_bee_canales'),
        ),
    ]
