# Generated by Django 4.2.7 on 2023-12-06 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0002_remove_tb_bee_canales_apikey_tb_bee_canales_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_bee_campos',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tb_bee_campos',
            name='fecha_actualizacion',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tb_bee_campos',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
