# Generated by Django 4.2.7 on 2023-12-10 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0003_tb_bee_campos_activo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TB_BEE_GRAFICA',
            fields=[
                ('idGrafica', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('ejeX', models.CharField(max_length=50)),
                ('ejeY', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=15)),
                ('backGround', models.CharField(max_length=15)),
                ('Tipo', models.CharField(max_length=30)),
                ('Datos', models.CharField(max_length=8)),
                ('idCanal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage.tb_bee_canales')),
            ],
            options={
                'db_table': 'TB_BEE_GRAFICA',
            },
        ),
    ]
