# Generated by Django 4.2.7 on 2023-12-11 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0005_remove_tb_bee_grafica_idcanal_tb_bee_grafica_idcampo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_bee_medidas',
            name='valor',
            field=models.FloatField(),
        ),
    ]
