# Generated by Django 4.2.7 on 2023-12-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0006_alter_tb_bee_medidas_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_bee_campos',
            name='urlName',
            field=models.CharField(default='fieldN', max_length=100),
            preserve_default=False,
        ),
    ]
